docker wf more

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,4 +1,4 @@
-name: Tag new version
+name: Create docker image
 
 on:
   push:
@@ -17,9 +17,15 @@ jobs:
         run: |
           docker --version
           pwd
-          ls -AFl
-          #docker build . --file Dockerfile --tag abaplint/abaplint:latest
+          docker build . --file Dockerfile --tag abaplint/abaplint:latest
       - name: Push container
         run: |
-          ls -AFl
           docker images
+          VERSION=$(docker run abaplint/abaplint:latest abaplint -v | tail -n 1)
+          [ -n "${VERSION}" ] || echo "Cannot identify abaplint version"
+          [ -n "${VERSION}" ] || exit 1
+          echo "abaplint version:" $VERSION
+          VERSION_2S=${VERSION%.*}
+          VERSION_1S=${VERSION_2S%.*}
+          echo "additional tags: $VERSION_2S, $VERSION_1S, latest"
+          ./bin/push-containers.sh
